KROGER_CLIENT_ID = "beansmeals-bbc7nxcc"
KROGER_CLIENT_SECRET = "BQLtwVhPhFMIHGPaZMKHe35YNtPsrK5cLdJ0fJdq"
SPOONACULAR_API_KEY = "566f8556333e4212ba2af19da916482d"
ZIP_CODE = "24712"
KROGER_BASE_URL = "https://api.kroger.com"
